#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_logrotate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep=".env.production"

chown -R $app:$app "$install_dir"

#=================================================
# SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Adding system configurations..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" --template="systemd.service"
yunohost service add "$app" --log "/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app... (this will take some time and resources!)"

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
